require_relative 'handlers/base.rb'
require_relative 'handlers/action_roll.rb'
require_relative 'handlers/effect_resolve.rb'
require_relative 'handlers/health_check.rb'
require_relative 'handlers/user_test.rb'
